// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreAppPhase2.DbContexts;

#nullable disable

namespace StoreAppPhase2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220806044558_UpdateSelling")]
    partial class UpdateSelling
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StoreAppPhase2.Entities.Employees", b =>
                {
                    b.Property<int>("IdEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEm"), 1L, 1);

                    b.Property<string>("AddressEm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstNameEm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastNameEm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RangeWorkingEm")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<decimal>("SalaryEm")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdEm");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("StoreAppPhase2.EntityModels.SellingEM", b =>
                {
                    b.Property<int>("SellingEMID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SellingEMID"), 1L, 1);

                    b.Property<int>("IdEM")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceID")
                        .HasColumnType("int");

                    b.Property<string>("StatusSellingEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SellingEMID");

                    b.HasIndex("IdEM");

                    b.ToTable("SellingEM");
                });

            modelBuilder.Entity("StoreAppPhase2.EntityModels.SellingEM", b =>
                {
                    b.HasOne("StoreAppPhase2.Entities.Employees", "employees")
                        .WithMany("SellingEMs")
                        .HasForeignKey("IdEM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employees");
                });

            modelBuilder.Entity("StoreAppPhase2.Entities.Employees", b =>
                {
                    b.Navigation("SellingEMs");
                });
#pragma warning restore 612, 618
        }
    }
}
